before:
  hooks:
    - go mod tidy
builds:
- goos:
    - linux
    - darwin
    - windows
  goarch:
    - arm64
    - amd64
  goarm:
    - "6"
  main: .
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
archives:
  -
    name_template: '{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
    files:
      - COPYING
      - README*
snapshot:
  name_template: "{{ incpatch .Version }}-next"
checksum:
  name_template: 'checksums.txt'
